"""TinyStories data loader for from-scratch pretraining.

TinyStories (Eldan & Li 2023, arXiv 2305.07759) is ~2GB of synthetic
children's stories generated by GPT-3.5/4. Designed exactly for
pretraining sub-50M-parameter models — they show that 33M models
trained on TinyStories produce coherent English. Perfect fit for our
24M PRISM-Lang architecture.

Hosted on HuggingFace as `roneneldan/TinyStories`.

This module:
  1. Downloads + caches TinyStories the first time
  2. Tokenizes the entire corpus using the GPT-2 BPE tokenizer
  3. Saves a single concatenated `.npy` token array per split for
     fast random sampling at training time

After tokenization (one-time, ~10-20 min on first run), training
loops just memmap the `.npy` and slice random windows.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np


# Cache layout:
#   ~/.cache/prism_lang_pretrain/tinystories/
#     train_tokens.npy   — int32 array, ~470M tokens (one big concat)
#     val_tokens.npy     — int32 array, ~5M tokens
TINYSTORIES_CACHE = Path.home() / ".cache" / "prism_lang_pretrain" / "tinystories"


def tokenize_and_cache(
    cache_dir: Path | None = None,
    *,
    tokenizer_name: str = "gpt2",
    eos_id: int = 50256,
    force: bool = False,
) -> tuple[Path, Path]:
    """Tokenize TinyStories and write to .npy. Idempotent — skips if
    already cached unless force=True. Returns (train_path, val_path)."""
    cache_dir = cache_dir or TINYSTORIES_CACHE
    cache_dir.mkdir(parents=True, exist_ok=True)
    train_path = cache_dir / "train_tokens.npy"
    val_path = cache_dir / "val_tokens.npy"

    if not force and train_path.exists() and val_path.exists():
        return train_path, val_path

    from datasets import load_dataset
    from prism.lang.tokenizer import get_tokenizer
    tok = get_tokenizer(tokenizer_name)

    print("[tinystories] downloading via HuggingFace datasets…")
    ds = load_dataset("roneneldan/TinyStories")

    for split, out_path in (("train", train_path), ("validation", val_path)):
        if not force and out_path.exists():
            print(f"[tinystories] {out_path} already exists, skipping")
            continue
        print(f"[tinystories] tokenizing {split} ({len(ds[split])} stories)…")
        # Concat all stories into one big int32 array, separated by EOS.
        # Use chunked encoding so we don't blow up RAM tokenizing 2GB at once.
        chunks: list[np.ndarray] = []
        chunk_size = 1000
        n = len(ds[split])
        for start in range(0, n, chunk_size):
            texts = [ex["text"] for ex in ds[split].select(
                range(start, min(start + chunk_size, n)))]
            # batched encoding is much faster than per-string
            ids_lists = tok(texts, add_special_tokens=False)["input_ids"]
            for ids in ids_lists:
                chunks.append(np.asarray(ids, dtype=np.int32))
                chunks.append(np.array([eos_id], dtype=np.int32))
            if (start // chunk_size) % 10 == 0:
                done = min(start + chunk_size, n)
                tot_so_far = sum(len(c) for c in chunks)
                print(f"  [{done:>7d}/{n}]  {tot_so_far/1e6:.1f}M tokens")

        all_tokens = np.concatenate(chunks)
        print(f"[tinystories] {split}: {len(all_tokens):,} tokens "
              f"({len(all_tokens) * 4 / 1e9:.2f} GB int32)")
        np.save(out_path, all_tokens)
        print(f"[tinystories] saved {out_path}")

    return train_path, val_path


class TokenSampler:
    """Memory-mapped sampler — yields random windows from a huge token
    array without loading the whole thing into RAM."""

    def __init__(self, token_path: Path, *, seq_len: int):
        self.tokens = np.load(token_path, mmap_mode="r")
        self.seq_len = seq_len
        self.n_tokens = len(self.tokens)
        if self.n_tokens < seq_len + 1:
            raise ValueError(
                f"token file has only {self.n_tokens} tokens, "
                f"need at least {seq_len + 1}"
            )

    def sample_batch(self, batch_size: int, rng: np.random.Generator
                     ) -> np.ndarray:
        """Returns (batch_size, seq_len) int64 array of token windows."""
        starts = rng.integers(0, self.n_tokens - self.seq_len - 1,
                              size=batch_size)
        out = np.zeros((batch_size, self.seq_len), dtype=np.int64)
        for i, s in enumerate(starts):
            out[i] = self.tokens[s:s + self.seq_len]
        return out

    def sample_windows(self, batch_size: int, seq_len: int,
                       rng: np.random.Generator) -> list[np.ndarray]:
        """Same as sample_batch but returns variable-length list (used by
        span corruption which produces different-length outputs per item)."""
        starts = rng.integers(0, self.n_tokens - seq_len - 1,
                              size=batch_size)
        return [np.asarray(self.tokens[s:s + seq_len]) for s in starts]


if __name__ == "__main__":
    train_path, val_path = tokenize_and_cache()
    print(f"\ntrain: {train_path}")
    print(f"val  : {val_path}")
