"""Cycle consistency loss for language head.

The fundamental problem: when an agent generates a description of what it
sees, what gradient should update the language head?

Solution: cycle consistency on CONCEPT EMBEDDINGS (not raw attention).

1. Agent observes scene → ConceptMemory returns concept embedding c_orig.
2. Language head generates text T from c_orig.
3. Re-encode T through a small text encoder → query vector q.
4. Query ConceptMemory with q → recovered concept embedding c_recovered.
5. Loss = MSE + cosine distance between c_recovered and c_orig.

Why concept embeddings, not attention weights?
- Attention is extracted via `get_association_matrix` which is wrapped in
  `@torch.no_grad()` upstream. No gradient flows.
- Concept embeddings come from the regular forward pass — fully
  differentiable. Gradient flows back through `encode_text` → text encoder
  weights, providing the training signal for grounded language production.

The semantic meaning is the same: "the text the model generates should let
me re-retrieve the same concept I started with."
"""

from __future__ import annotations

import torch
import torch.nn as nn
import torch.nn.functional as F


class CycleConsistencyLoss(nn.Module):
    """Cycle: concept → text → text encoder → recovered concept.

    The text encoder is a small trainable module that takes generated text
    tokens and produces a query vector compatible with ConceptMemory's input.
    """

    def __init__(
        self,
        vocab_size: int,
        text_emb_dim: int = 128,
        hidden_dim: int = 192,
        latent_dim: int = 128,
        pad_idx: int = 0,
        n_layers: int = 2,
        n_heads: int = 4,
    ):
        super().__init__()
        self.pad_idx = pad_idx

        if text_emb_dim % n_heads != 0:
            valid = [n for n in (1, 2, 4, 6, 8, 12, 16) if text_emb_dim % n == 0]
            raise ValueError(
                f"CycleConsistencyLoss: text_emb_dim ({text_emb_dim}) must be "
                f"divisible by n_heads ({n_heads}). Valid n_heads: {valid}"
            )

        # Small bidirectional encoder for text → vector.
        self.token_embed = nn.Embedding(vocab_size, text_emb_dim, padding_idx=pad_idx)
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=text_emb_dim,
            nhead=n_heads,
            dim_feedforward=hidden_dim,
            batch_first=True,
            norm_first=True,
            dropout=0.1,
        )
        # enable_nested_tensor=False silences the warning that fires when
        # norm_first=True (nested tensors aren't compatible with pre-norm).
        self.text_encoder = nn.TransformerEncoder(
            encoder_layer,
            num_layers=n_layers,
            enable_nested_tensor=False,
        )
        self.query_proj = nn.Linear(text_emb_dim, latent_dim)

    def encode_text(self, text_tokens: torch.Tensor) -> torch.Tensor:
        """text_tokens: (B, T) long → (B, latent_dim) query vector."""
        mask = (text_tokens == self.pad_idx)
        # Avoid all-pad rows (would NaN the mean).
        if mask.all(dim=-1).any():
            mask = mask.clone()
            mask[:, 0] = False  # at least one position is non-pad
        emb = self.token_embed(text_tokens)
        h = self.text_encoder(emb, src_key_padding_mask=mask)
        # Mean-pool over non-pad positions.
        valid = (~mask).unsqueeze(-1).float()
        pooled = (h * valid).sum(dim=1) / (valid.sum(dim=1) + 1e-8)
        return self.query_proj(pooled)

    def forward(
        self,
        text_tokens: torch.Tensor,             # (B, T) generated tokens
        concept_memory: nn.Module,             # ConceptMemory instance
        original_concept: torch.Tensor,        # (B, slot_dim) target concept
        mse_weight: float = 1.0,
        cos_weight: float = 1.0,
    ) -> dict[str, torch.Tensor]:
        """Compute cycle consistency loss.

        text_tokens: tokens generated by the language head.
        concept_memory: the ConceptMemory the original concept came from.
        original_concept: the (B, slot_dim) concept embedding before text was
                          generated. Will be detached internally — we only
                          backprop through the recovered path.
        """
        # Re-encode text → query vector.
        q = self.encode_text(text_tokens)  # (B, latent_dim), has grad

        # Query ConceptMemory with the re-encoded text.
        # This uses the regular forward path → gradient flows.
        recovered_concept = concept_memory(q, return_attention=False)
        # recovered_concept: (B, slot_dim), has grad

        target = original_concept.detach()

        mse = F.mse_loss(recovered_concept, target)
        cos = 1.0 - F.cosine_similarity(
            recovered_concept, target, dim=-1
        ).mean()

        total = mse_weight * mse + cos_weight * cos

        return {
            "cycle_loss": total,
            "mse": mse.detach(),
            "cos": cos.detach(),
            "recovered_concept": recovered_concept.detach(),
        }
