"""Cycle consistency loss for language head.

The fundamental problem: when an agent generates a description of what it
sees, what gradient should update the language head?

Solution: cycle consistency.
1. Agent observes scene → ConceptMemory activates slots S = {s1, s2, ...}
2. Language head generates text T from those slots
3. We RE-ENCODE T through a text encoder back to a "query vector" q
4. We query ConceptMemory with q → should activate the SAME slots S
5. Loss = how much the cycle-encoded slots differ from the originals

This gives gradient signal for the language head without external supervision.
The text the model generates is "useful" if it can be used to recover the same
concept activations — that's the empirical definition of correct grounding.
"""

from __future__ import annotations

import torch
import torch.nn as nn
import torch.nn.functional as F


class CycleConsistencyLoss(nn.Module):
    """Cycle: concept activations → text → text encoder → concept activations.

    The text encoder is a small trainable module that takes generated text
    tokens and produces a query vector compatible with ConceptMemory's input.
    """

    def __init__(
        self,
        vocab_size: int,
        text_emb_dim: int = 128,
        hidden_dim: int = 192,
        latent_dim: int = 128,
        pad_idx: int = 0,
        n_layers: int = 2,
        n_heads: int = 4,
    ):
        super().__init__()
        self.pad_idx = pad_idx

        # Small bidirectional encoder for text → vector.
        self.token_embed = nn.Embedding(vocab_size, text_emb_dim, padding_idx=pad_idx)
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=text_emb_dim,
            nhead=n_heads,
            dim_feedforward=hidden_dim,
            batch_first=True,
            norm_first=True,
            dropout=0.1,
        )
        self.text_encoder = nn.TransformerEncoder(encoder_layer, num_layers=n_layers)
        self.query_proj = nn.Linear(text_emb_dim, latent_dim)

    def encode_text(self, text_tokens: torch.Tensor) -> torch.Tensor:
        """text_tokens: (B, T) long → (B, latent_dim) query vector."""
        mask = (text_tokens == self.pad_idx)
        emb = self.token_embed(text_tokens)
        h = self.text_encoder(emb, src_key_padding_mask=mask)
        # Mean-pool over non-pad positions.
        valid = (~mask).unsqueeze(-1).float()
        pooled = (h * valid).sum(dim=1) / (valid.sum(dim=1) + 1e-8)
        return self.query_proj(pooled)

    def forward(
        self,
        text_tokens: torch.Tensor,             # (B, T) generated tokens
        concept_memory: nn.Module,             # ConceptMemory instance
        original_attention: torch.Tensor,      # (B, n_slots) target attention
        kl_weight: float = 1.0,
    ) -> dict[str, torch.Tensor]:
        """Compute cycle consistency loss.

        text_tokens: tokens generated by the language head.
        concept_memory: the ConceptMemory the original attention came from.
        original_attention: softmax over slots before text was generated.
        """
        # Re-encode text → query vector.
        q = self.encode_text(text_tokens)  # (B, latent_dim)

        # Query ConceptMemory with the re-encoded text.
        _, recovered_attn = concept_memory(q, return_attention=True)
        # recovered_attn shape: (B, n_slots)

        # KL divergence between original and recovered attention distributions.
        # Treat attention as probabilities (it's already softmax).
        eps = 1e-8
        orig = original_attention + eps
        orig = orig / orig.sum(dim=-1, keepdim=True)
        recov = recovered_attn + eps
        recov = recov / recov.sum(dim=-1, keepdim=True)

        kl = F.kl_div(
            input=torch.log(recov),
            target=orig,
            reduction="batchmean",
        )

        # Also include cosine similarity loss for stability.
        cos = 1.0 - F.cosine_similarity(
            original_attention, recovered_attn, dim=-1
        ).mean()

        total = kl_weight * kl + cos

        return {
            "cycle_loss": total,
            "kl": kl.detach(),
            "cos": cos.detach(),
            "recovered_attention": recovered_attn.detach(),
        }
